site_name: All About the Homelab | Infrastructure Documentation
site_description: Internal homelab documentation
site_url: https://ahnaj.github.io/homelab-docs/

theme:
  name: material
  custom_dir: overrides
  font:
    text: Ubuntu Mono
    code: Ubuntu Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
  palette:
    - scheme: slate

extra_css:
  - stylesheets/console.css

extra_javascript:
  - javascripts/carousel.js
  - javascripts/cli-nav.js

nav:
  - Overview: index.md
  - Hardware: hardware.md
  - 3D Models: 3d-models.md
  - Print Server: print-server.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables

plugins:
  - search